export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS"
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS"
export const SELECT_ACCOUNT_SUCCESS = "SELECT_ACCOUNT_SUCCESS"
export const MINING_SUCCESS = "MINING_SUCCESS"