export const ACCOUNT_REQUEST = "ACCOUNT_REQUEST"
export const ACCOUNT_SUCCESS = "ACCOUNT_SUCCESS"
export const ACCOUNT_FAILURE = "ACCOUNT_FAILURE"

export const SELECT_ACCOUNT_REQUEST = "SELECT_ACCOUNT_REQUEST"
export const SELECT_ACCOUNT_SUCCESS = "SELECT_ACCOUNT_SUCCESS"
export const SELECT_ACCOUNT_FAILURE = "SELECT_ACCOUNT_FAILURE"