export const ACCOUNT_REQUEST = "ACCOUNT_REQUEST"
export const ACCOUNT_SUCCESS = "ACCOUNT_SUCCESS"
export const ACCOUNT_FAILURE = "ACCOUNT_FAILURE"

export const GET_ACCOUNT_REQUEST = "GET_ACCOUNT_REQUEST"
export const GET_ACCOUNT_SUCCESS = "GET_ACCOUNT_SUCCESS"
export const GET_ACCOUNT_FAILURE = "GET_ACCOUNT_FAILURE"