export const MNEMONIC_REQUEST = "MNEMONIC_REQUEST"
export const MNEMONIC_SUCCESS = "MNEMONIC_SUCCESS"
export const MNEMONIC_FAILURE = "MNEMONIC_FAILURE"

export const POST_MNEMONIC_REQUEST = "POST_MNEMONIC_REQUEST"
export const POST_MNEMONIC_SUCCESS = "POST_MNEMONIC_SUCCESS"
export const POST_MNEMONIC_FAILURE = "POST_MNEMONIC_FAILURE"