export const CREATE_WALLET_REQUEST = "CREATE_WALLET_REQUEST"
export const CREATE_WALLET_SUCCESS = "CREATE_WALLET_SUCCESS"
export const CREATE_WALLET_FAILURE = "CREATE_WALLET_FAILURE"

export const CREATE_ACCOUNT_REQUEST = "CREATE_ACCOUNT_REQUEST"
export const CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS"
export const CREATE_ACCOUNT_FAILURE = "CREATE_ACCOUNT_FAILURE"

export const GET_WALLET_REQUEST = "GET_WALLET_REQUEST"
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS"
export const GET_WALLET_FAILURE = "GET_WALLET_FAILURE"